donasi/urls.py
from django.urls import re_path
from donasi.views import daftar_program_donasi, detail_program_donasi, daftar_donatur_program_donasi

app_name = 'donasi'

urlpatterns = [
    re_path(r'^program-donasi/$', daftar_program_donasi, name='daftar-program-donasi'),
    re_path(r'^program-donasi/(?P<pk>[0-9]+)/$', detail_program_donasi, name='detail-program-donasi'),
    re_path(r'^program-donasi/(?P<pk>[0-9]+)/donatur$', daftar_donatur_program_donasi, name='daftar-donatur-program-donasi'),
]

ppw/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import re_path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('akun.urls', namespace='akun')),
    re_path(r'^', include('berita.urls', namespace='berita')),
    re_path(r'^', include('donasi.urls', namespace='donasi')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

donasi/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator

from berita.models import Berita

class ProgramDonasi(models.Model):
    inisiator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='daftar_program_donasi')
    berita_terkait = models.ForeignKey(Berita, on_delete=models.SET_NULL, blank=True, null=True, related_name='daftar_program_donasi')
    judul = models.CharField(max_length=300)
    deskripsi = models.TextField()
    link_gambar = models.URLField(blank=True)
    target_donasi = models.PositiveIntegerField(validators=[MinValueValidator(1)])

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name = 'Program Donasi'
        verbose_name_plural = 'Program Donasi'

class Donasi(models.Model):
    program_donasi = models.ForeignKey(ProgramDonasi, on_delete=models.CASCADE, related_name='daftar_donasi')
    donatur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='daftar_donasi')
    nama = models.CharField(max_length=300, default='Anonim')
    jumlah_donasi = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    anonim = models.BooleanField(default=True)

    def __str__(self):
        return 'Donasi ' + self.donatur.name + ' untuk ' + str(self.program_donasi)

    class Meta:
        verbose_name = 'Donasi'
        verbose_name_plural = 'Donasi'

donasi/forms.py
from django import forms
from donasi.models import Donasi

class DonasiForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'type': 'email', 'class': 'form-control'}))

    class Meta:
        model = Donasi
        fields = ['program_donasi', 'donatur', 'nama', 'email', 'jumlah_donasi', 'anonim']
        widgets = {
            'program_donasi': forms.Select(attrs={'class': 'form-control'}),
            'donatur': forms.Select(attrs={'class': 'form-control'}),
            'nama': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'jumlah_donasi': forms.NumberInput(attrs={'class': 'form-control'}),
            'anonim': forms.CheckboxInput(),
        }
        

donasi/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import get_user_model

from donasi.models import ProgramDonasi, Donasi
from donasi.forms import DonasiForm

def daftar_program_donasi(request):
    pd_list = ProgramDonasi.objects.all()
    for pd in pd_list:
        pd.target_donasi = format(pd.target_donasi, ",")

    response = {
        'pd_list': pd_list
    }

    return render(request, 'donasi/daftar_program_donasi.html', response)

def detail_program_donasi(request, pk):
    pd_detail = get_object_or_404(ProgramDonasi, pk=pk)
    pd_detail.target_donasi = format(pd_detail.target_donasi, ",")
    donasi_form = DonasiForm()
    error_akun = None

    if request.method == 'POST':
        data = request.POST.copy()
        data['program_donasi'] = pd_detail.id
        try:
            data['donatur'] = get_user_model().objects.get(email=data['email']).id
        except ObjectDoesNotExist:
            data['donatur'] = None
            error_akun = 'Akun dengan email tersebut tidak ditemukan!'
        donasi_form = DonasiForm(data=data)
        if donasi_form.is_valid():
            donasi_form.save()
            return render(request, 'donasi/donasi_sukses.html', {'pd_detail': pd_detail})

    response = {
        'pd_detail': pd_detail,
        'donasi_form': donasi_form,
        'error_akun': error_akun
    }
    return render(request, 'donasi/detail_program_donasi.html', response)

def daftar_donatur_program_donasi(request, pk):
    pd_detail = get_object_or_404(ProgramDonasi, pk=pk)
    pd_detail.target_donasi = format(pd_detail.target_donasi, ",")

    daftar_donasi = Donasi.objects.filter(program_donasi=pd_detail)
    for donasi in daftar_donasi:
        donasi.jumlah_donasi = format(donasi.jumlah_donasi, ",")
        if donasi.anonim:
            donasi.nama = 'Anonim'

    response = {
        'pd_detail': pd_detail,
        'daftar_donasi': daftar_donasi
    }
    return render(request, 'donasi/daftar_donatur_program_donasi.html', response)

donasi/templates/donasi/daftar_donatur_program_donasi.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'donasi/styles/donasi.css' %}">
    <title>Daftar Donatur {{ pd_detail.judul }} - Perak Funding</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="card text-white bg-green-dark">
                    <img class="card-img-top" src="{{ pd_detail.link_gambar }}" alt="Program Donasi Image">
                    <div class="card-header">
                        {{ pd_detail.judul }}
                    </div>
                    <div class="card-body">
                        <p>{{ pd_detail.deskripsi }}</p>
                    </div>
                    <div class="card-upper-footer">
                        <ul class="fa-ul">
                            <li class="card-text"><span class="fa-li" ><i class="fas fa-money-bill-alt"></i></span>: Rp. {{ pd_detail.target_donasi }}</li>
                            <li class="card-text"><span class="fa-li" ><i class="fas fa-user-circle"></i></span>: {{ pd_detail.inisiator.name }}</li>
                        </ul>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'donasi:detail-program-donasi' pd_detail.id %}" class="btn bg-green-light">
                            <button class="btn bg-green-light">Donasi</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card text-white bg-green-dark">
                    <div class="card-header">
                        <h1>Daftar donatur</h1>
                    </div>
                    <div class="card-body">
                        {% if daftar_donasi %}
                        <ul>
                            {% for donasi in daftar_donasi %}
                            <li class="card-text">
                                {{ donasi.nama }}, sebesar Rp. {{ donasi.jumlah_donasi }}
                            </li>
                            {% endfor %}
                        </ul>
                        {% else %}
                        <h3>Belum ada yang berdonasi untuk program ini.</h3>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

donasi/templates/donasi/daftar_program_donasi.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'donasi/styles/donasi.css' %}">
    <title>Daftar Program Donasi - Perak Funding</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% if pd_list %}
                <div class="card-deck">
                    {% for pd in pd_list %}
                    <div class="card flex-item-3 text-white bg-green-dark">
                        <img class="card-img-top" src="{{ pd.link_gambar }}" alt="Program Donasi Image">
                        <div class="card-header">
                            {{ pd.judul }}
                        </div>
                        <div class="card-body">
                            <p>{{ pd.deskripsi }}</p>
                        </div>
                        <div class="card-upper-footer">
                            <ul class="fa-ul">
                                <li class="card-text"><span class="fa-li" ><i class="fas fa-money-bill-alt"></i></span>: Rp. {{ pd.target_donasi }}</li>
                                <li class="card-text"><span class="fa-li" ><i class="fas fa-user-circle"></i></span>: {{ pd.inisiator.name }}</li>
                            </ul>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'donasi:detail-program-donasi' pd.id %}" class="btn bg-green-light">
                                <button class="btn bg-green-light">Donasi</button>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jumbotron bg-green-dark text-white text-justify">
                    <h1>Belum ada program donasi yang bisa anda ikuti</h1>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

donasi/templates/donasi/detail_program_donasi.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'donasi/styles/donasi.css' %}">
    <title>{{ pd_detail.judul }} - Perak Funding</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="card text-white bg-green-dark">
                    <img class="card-img-top" src="{{ pd_detail.link_gambar }}" alt="Program Donasi Image">
                    <div class="card-header">
                        {{ pd_detail.judul }}
                    </div>
                    <div class="card-body">
                        <p>{{ pd_detail.deskripsi }}</p>
                    </div>
                    <div class="card-upper-footer">
                        <ul class="fa-ul">
                            <li class="card-text"><span class="fa-li" ><i class="fas fa-money-bill-alt"></i></span>: Rp. {{ pd_detail.target_donasi }}</li>
                            <li class="card-text"><span class="fa-li" ><i class="fas fa-user-circle"></i></span>: {{ pd_detail.inisiator.name }}</li>
                        </ul>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'donasi:daftar-donatur-program-donasi' pd_detail.id %}" class="btn bg-green-light">
                            <button class="btn bg-green-light">Daftar Donatur</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card text-white bg-green-dark">
                    <div class="card-header">
                        <h1>Mari berdonasi!</h1>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'donasi:detail-program-donasi' pd_detail.id %}" method="POST">
                            {% csrf_token %}
                            {{ donasi_form.program_donasi.as_hidden }}
                            {{ donasi_form.donatur.as_hidden }}
                            {% if error_akun %}
                            <p>{{ error_akun }}</p>
                            {% endif %}
                            <div class="form-group">
                                {{ donasi_form.nama.label_tag }}
                                {{ donasi_form.nama }}
                            </div>
                            <div class="form-group">
                                {{ donasi_form.email.label_tag }}
                                {{ donasi_form.email }}
                            </div>
                            <div class="form-group">
                                {{ donasi_form.jumlah_donasi.label_tag }}
                                {{ donasi_form.jumlah_donasi }}
                            </div>
                            <span>{{ donasi_form.anonim }} Saya tidak ingin nama saya ditunjukkan di daftar donatur</span>
                            <button type="submit" class="save btn bg-green-light">Donasi</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

donasi/templates/donasi/donasi_sukses.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'donasi/styles/donasi.css' %}">
    <title>Donasi Sukses - Perak Funding</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="jumbotron bg-green-dark text-white text-justify">
                <h1>Donasi sukses dilakukan!</h1>
                <p class="lead">
                    Anda akan diarahkan ke halaman daftar donatur dalam 5 detik. 
                    Silakan klik di <a href="{% url 'donasi:daftar-donatur-program-donasi' pd_detail.id %}">sini</a> jika browser Anda tidak mengarahkan Anda.
                </p>
            </div>
        </div>
    </div>
    <script>
        function redirect(){
            window.location.href = "{% url 'donasi:daftar-donatur-program-donasi' pd_detail.id %}";
        }
    
        setTimeout(redirect, 3000);
    </script>
{% endblock %}