berita/urls.py
from django.urls import re_path
from berita.views import daftar_berita, daftar_program_donasi_dari_berita

app_name = 'berita'

urlpatterns = [
    re_path(r'^berita/$', daftar_berita, name='daftar-berita'),
    re_path(r'^berita/(?P<pk>[0-9]+)/daftar-program-donasi/$', daftar_program_donasi_dari_berita, name='daftar-program-donasi-dari-berita'),
]

donasi/urls.py
from django.urls import re_path
from donasi.views import daftar_program_donasi, detail_program_donasi, daftar_donatur_program_donasi

app_name = 'donasi'

urlpatterns = [
    re_path(r'^program-donasi/$', daftar_program_donasi, name='daftar-program-donasi'),
    re_path(r'^program-donasi/(?P<pk>[0-9]+)/$', detail_program_donasi, name='detail-program-donasi'),
    re_path(r'^program-donasi/(?P<pk>[0-9]+)/donatur$', daftar_donatur_program_donasi, name='daftar-donatur-program-donasi'),
]

ppw/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import re_path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('akun.urls', namespace='akun')),
    re_path(r'^', include('berita.urls', namespace='berita')),
    re_path(r'^', include('donasi.urls', namespace='donasi')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

berita/models.py
from django.db import models

class Berita(models.Model):
    judul = models.CharField(max_length=300)
    deskripsi = models.TextField()
    link_gambar = models.URLField(blank=True)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name = 'Berita'
        verbose_name_plural = 'Berita'

berita/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Count

from berita.models import Berita
from donasi.models import ProgramDonasi

def daftar_berita(request):
    berita_list = Berita.objects.annotate(jumlah_program_donasi=Count('daftar_program_donasi'))

    response = {
        'berita_list': berita_list
    }

    return render(request, 'berita/daftar_berita.html', response)

def daftar_program_donasi_dari_berita(request, pk):
    berita = get_object_or_404(Berita, pk=pk)
    daftar_program_donasi = ProgramDonasi.objects.filter(berita_terkait=berita)
    for pd in daftar_program_donasi:
        pd.target_donasi = format(pd.target_donasi, ",")

    response = {
        'berita': berita,
        'daftar_program_donasi' : daftar_program_donasi
    }

    return render(request, 'berita/daftar_program_donasi_dari_berita.html', response)

berita/templates/berita/daftar_berita.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'berita/styles/berita.css' %}">
    <title>Daftar Berita - Perak Funding</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% if berita_list %}
                <div class="card-deck">
                    {% for berita in berita_list %}
                    <div class="card flex-item-3 text-white bg-green-dark">
                        <img class="card-img-top" src="{{ berita.link_gambar }}" alt="News Image">
                        <div class="card-header">
                            <h1>{{ berita.judul }}</h1>
                        </div>
                        <div class="card-body">
                            <p>{{ berita.deskripsi }}</p>
                        </div>
                        <div class="card-footer">
                            {% if not berita.jumlah_program_donasi %}
                            <p class="alert alert-danger"> 
                                <strong>Maaf, </strong>belum ada Program Donasi yang terkait dengan berita ini.
                            </p>
                            {% else %}
                            <p class="alert alert-success">
                                <strong>Donasi Sekarang!</strong> Lihat daftar program donasi yang ada dapat ikuti.
                            </p>
                            <a href="{% url 'berita:daftar-program-donasi-dari-berita' berita.id %}" class="btn bg-green-light">
                                <button class="btn bg-green-light">Daftar Program Donasi</button>
                            </a>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jumbotron bg-green-dark text-white text-justify">
                    <h1>Belum ada berita apapun saat ini</h1>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

berita/templates/berita/daftar_program_donasi_dari_berita.html
{% extends 'base.html' %}
{% load static %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'berita/styles/berita.css' %}">
    <title>Program Donasi Terkait {{ berita.judul }} - Perak Funding</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="card flex-item-3 text-white bg-green-dark">
                    <img class="card-img-top" src="{{ berita.link_gambar }}" alt="News Image">
                    <div class="card-header">
                        <h1>{{ berita.judul }}</h1>
                    </div>
                    <div class="card-body">
                        <p>{{ berita.deskripsi }}</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 text-white">
                {% if daftar_program_donasi %}
                <h1>Program Donasi yang terkait</h1>
                <div class="card-deck">
                    {% for pd in daftar_program_donasi %}
                    <div class="card flex-item-1 text-white bg-green-dark">
                        <img class="card-img-top" src="{{ pd.link_gambar }}" alt="Program Donasi Image">
                        <div class="card-header">
                            {{ pd.judul }}
                        </div>
                        <div class="card-body">
                            <p>{{ pd.deskripsi }}</p>
                        </div>
                        <div class="card-upper-footer">
                            <ul class="fa-ul">
                                <li class="card-text"><span class="fa-li" ><i class="fas fa-money-bill-alt"></i></span>: Rp. {{ pd.target_donasi }}</li>
                                <li class="card-text"><span class="fa-li" ><i class="fas fa-user-circle"></i></span>: {{ pd.inisiator.name }}</li>
                            </ul>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'donasi:detail-program-donasi' pd.id %}" class="btn bg-green-light">
                                <button class="btn bg-green-light">Donasi</button>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="jumbotron bg-green-dark text-white text-justify">
                    <h1>Tidak ada Program Donasi yang terkait dengan berita ini</h1>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}