akun/urls.py
from django.urls import re_path
from akun.views import homepage, registrasi

app_name = 'akun'

urlpatterns = [
    re_path(r'^$', homepage, name='homepage'),
    re_path(r'^registrasi/$', registrasi, name='registrasi'),
]

berita/urls.py
from django.urls import re_path
from berita.views import daftar_berita, daftar_program_donasi_dari_berita

app_name = 'berita'

urlpatterns = [
    re_path(r'^berita/$', daftar_berita, name='daftar-berita'),
    re_path(r'^berita/(?P<pk>[0-9]+)/daftar-program-donasi/$', daftar_program_donasi_dari_berita, name='daftar-program-donasi-dari-berita'),
]

donasi/urls.py
from django.urls import re_path
from donasi.views import daftar_program_donasi, detail_program_donasi, daftar_donatur_program_donasi

app_name = 'donasi'

urlpatterns = [
    re_path(r'^program-donasi/$', daftar_program_donasi, name='daftar-program-donasi'),
    re_path(r'^program-donasi/(?P<pk>[0-9]+)/$', detail_program_donasi, name='detail-program-donasi'),
    re_path(r'^program-donasi/(?P<pk>[0-9]+)/donatur$', daftar_donatur_program_donasi, name='daftar-donatur-program-donasi'),
]

ppw/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import re_path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('akun.urls', namespace='akun')),
    re_path(r'^', include('berita.urls', namespace='berita')),
    re_path(r'^', include('donasi.urls', namespace='donasi')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common_files/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/logo.png'%}"/>
        {% block additional_head %}
        {% endblock %}
    </head>
    <body class="bg-grey">
        {% include 'header.html' %}
        {% block content %}
        {% endblock %}
        {% include 'footer.html' %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

common_files/templates/footer.html
<footer class="footer bg-green-light text-white">
    <div class="d-flex flex-wrap bg-green-light">
        <div class="col-sm-2">
            <ul class="list-unstyled">
                <li><h3>Perak Funding</h3></li>
                <li>About Us</li>
            </ul>
        </div>
        <div class="col-sm-4">
            <ul class="list-unstyled">
                <li><h4>Contact Us</h4></li>
                <li>Phone : +021 xxxxxxx</li>
                <li>Email : contact@perakfunding.com</li>
            </ul>
        </div>
        </div>
    </div>
</footer>

common_files/templates/header.html
{% load static %}
<nav class="header navbar navbar-expand-lg sticky-top navbar-dark bg-green-light">
    <a class="navbar-brand" href="{% url 'akun:homepage' %}">
        Perak Funding
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active {% if request.resolver_match.url_name == 'daftar-program-donasi' %}active-nav-item{% endif %}">
                <a class="nav-link" href="{% url 'donasi:daftar-program-donasi' %}">Program Donasi</a>
            </li>
            <li class="nav-item active {% if request.resolver_match.url_name == 'daftar-berita' %}active-nav-item{% endif %}">
                <a class="nav-link" href="{% url 'berita:daftar-berita' %}">Berita</a>
            </li>
        </ul>
        <ul class="navbar-nav justify-content-end">
            <li class="nav-item active {% if request.resolver_match.url_name == 'registrasi' %}active-nav-item{% endif %}">
                <a class="nav-link" href="{% url 'akun:registrasi' %}">Registrasi</a>
            </li>
        </ul>
    </div>
</nav>

common_files/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block additional_head %}
    <title>Perak Funding</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron bg-green-dark text-white text-justify">
            <div class="row">
                <div class="col-sm-4">
                    <img src="{% static 'images/logo.png' %}" class="img-fluid rounded" alt="Logo">
                </div>
                <div class="col-sm-8">
                    <h1>Gabung dan jadilah bagian dari perubahan!</h1>
                    <p class="lead">
                        Perak Funding memfasilitasi anda yang berjiwa sosial untuk membantu saudara-saudara kita yang membutuhkan
                        dengan transparansi yang jelas.
                    </p>
                    <p>Jadi, tunggu apa lagi? Daftar sekarang!.</p>
                    <p class="lead">
                        <a class="btn btn-lg bg-green-light text-white" href="{% url 'akun:registrasi' %}" role="button">Register</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="spacer"></div>
    </div>
{% endblock %}